server.port=8080

# ===========================
# PostgreSQL / Amazon RDS
# ===========================
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME:pedidosdb}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.hikari.connection-timeout=10000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===========================
# Microsoft Entra ID / JWT
# ===========================
# Directory (tenant) ID. No usar el Client ID aquí.
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/84e517e6-6e52-43b3-82da-162220153ea3/v2.0

# Application (client) ID de la App Registration de la API.
spring.security.oauth2.resourceserver.jwt.audiences[0]=d7a99a6a-b387-494e-a239-5ea101bb3856

# ===========================
# Aplicación
# ===========================
spring.application.name=pedidos-api-semana05

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs